clk: msm: Fix literal-conversion warnings
../drivers/clk/msm/clock-gcc-8996.c:201:33: error: implicit conversion from 'double' to '_Bool' changes value from 2.5 to true [-Werror,-Wliteral-conversion]
        F( 240000000, gpll0_out_main,  2.5,    0,     0),
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
../drivers/clk/msm/clock-gcc-8996.c:53:41: note: expanded from macro 'F'
                .div_src_val = BVAL(4, 0, (int)FIXDIV(div)) \
                                               ~~~~~~~^~~~
../drivers/clk/msm/clock-gcc-8996.c:44:22: note: expanded from macro 'FIXDIV'
#define FIXDIV(div) (div ? (2 * (div) - 1) : (0))
                     ^~~ ~
../include/linux/clk/msm-clk-provider.h:36:32: note: expanded from macro 'BVAL'
#define BVAL(msb, lsb, val)     (((val) << lsb) & BM(msb, lsb))

Signed-off-by: Albert I <krascgq@outlook.co.id>
[@nathanchance: Make title more descriptive and fix warning text]
Signed-off-by: Nathan Chancellor <natechancellor@gmail.com>

(cherry picked from commit b446508dfb20bae81ea3a5875009994bd3c8fc9f)