include: sound: Fix timespec header issue
This fixes:

error: field has incomplete type 'struct timespec'

when including asound.h.

Change-Id: I0caf447fbb7dac21b567a2a80f3f6e83b6fe4e4e
(cherry picked from commit c8a9214b6bd8e8175d052be9a316149334c96635)